services:
  shared_calculator_leader:
    build:
      context: .
      dockerfile: shared_calculator/shared_calculator_leader/Dockerfile
    ports:
      - "50051:50051"
    command: ["tail", "-f", "/dev/null"]

  shared_calculator_replica:
    build:
      context: .
      dockerfile: shared_calculator/shared_calculator_replica/Dockerfile
    depends_on:
      - shared_calculator_leader
    command: ["tail", "-f", "/dev/null"]