services:
  shared_calculator_leader:
    build:
      context: .
      dockerfile: shared_calculator_leader/Dockerfile
    # keep container alive without executing binary
    command: ["tail", "-f", "/dev/null"]

  shared_calculator_replica:
    build:
      context: .
      dockerfile: shared_calculator_replica/Dockerfile
    # keep container alive without executing binary
    command: ["tail", "-f", "/dev/null"]
